apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: 706274417810.dkr.ecr.ap-south-1.amazonaws.com/springboot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-svc
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
